### ISSUE TITLE
Set up Eclipse, step 4 not found

### ISSUE THREAD

**Issue by ElisaRojas** [fp7-netide/IDE#20]
Hi,

I was reinstalling the IDE from scratch and I had to stop at step 4, because http://updatesite.netide.eu/dependencies is not loading.

![ide4](https://cloud.githubusercontent.com/assets/2779496/17021908/4b46145a-4f4b-11e6-9769-540845fbcc5e.png)

@cstritzke , is this ok? I guess not, but just in case the README is not updated. Could you indicate the packages I need to install manually?

Any help would be really appreciated!
Thank you.

**Comment by cstritzke** [comment]
There's a problem with the update site server. With a bit of luck, it will be fixed tomorrow.
Meanwhile, you can build the update site from source. You'll need the newest copy of the master branch and follow the steps described [here](https://github.com/fp7-netide/IDE/wiki/Installation#by-building-from-source).

**Comment by ElisaRojas** [comment]
Thank you @cstritzke ,

I tried installing manually, but I got the following error when executing `MAVEN_OPTS="-Xmx1024M" mvn package`:

```
[ERROR] Internal error: java.lang.RuntimeException: org.apache.maven.MavenExecutionException: Could not setup plugin ClassRealm: Plugin org.eclipse.tycho:tycho-source-plugin:0.23.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-source-plugin:jar:0.23.0 -> org.apache.maven.plugins:maven-source-plugin:jar:2.1: Failed to read artifact descriptor for org.apache.maven.plugins:maven-source-plugin:jar:2.1: Could not transfer artifact org.apache.maven.plugins:maven-source-plugin:pom:2.1 from/to central (https://repo.maven.apache.org/maven2): /home/netide/.m2/repository/org/apache/maven/plugins/maven-source-plugin/2.1/maven-source-plugin-2.1.pom.part.lock (No such file or directory) -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.apache.maven.MavenExecutionException: Could not setup plugin ClassRealm
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: org.apache.maven.MavenExecutionException: Could not setup plugin ClassRealm
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.getDependencyMetadata(P2DependencyResolver.java:174)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.setupProjects(P2DependencyResolver.java:130)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.setupProject(DefaultTychoResolver.java:96)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:90)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    ... 11 more
Caused by: org.apache.maven.MavenExecutionException: Could not setup plugin ClassRealm
    at org.eclipse.tycho.core.maven.utils.PluginRealmHelper.newMavenExecutionException(PluginRealmHelper.java:154)
    at org.eclipse.tycho.core.maven.utils.PluginRealmHelper.execute(PluginRealmHelper.java:141)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.getDependencyMetadata(P2DependencyResolver.java:152)
    ... 17 more
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.eclipse.tycho:tycho-source-plugin:0.23.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.tycho:tycho-source-plugin:jar:0.23.0 -> org.apache.maven.plugins:maven-source-plugin:jar:2.1
    at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:214)
    at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:149)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:400)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:372)
    at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:231)
    at org.eclipse.tycho.core.maven.utils.PluginRealmHelper.execute(PluginRealmHelper.java:123)
    ... 18 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.eclipse.tycho:tycho-source-plugin:jar:0.23.0 -> org.apache.maven.plugins:maven-source-plugin:jar:2.1
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
    at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:202)
    ... 23 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.apache.maven.plugins:maven-source-plugin:jar:2.1
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:282)
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
    ... 25 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.apache.maven.plugins:maven-source-plugin:pom:2.1 from/to central (https://repo.maven.apache.org/maven2): /home/netide/.m2/repository/org/apache/maven/plugins/maven-source-plugin/2.1/maven-source-plugin-2.1.pom.part.lock (No such file or directory)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
    ... 32 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.maven.plugins:maven-source-plugin:pom:2.1 from/to central (https://repo.maven.apache.org/maven2): /home/netide/.m2/repository/org/apache/maven/plugins/maven-source-plugin/2.1/maven-source-plugin-2.1.pom.part.lock (No such file or directory)
    at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
    at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
    ... 35 more
Caused by: java.io.FileNotFoundException: /home/netide/.m2/repository/org/apache/maven/plugins/maven-source-plugin/2.1/maven-source-plugin-2.1.pom.part.lock (No such file or directory)
    at java.io.RandomAccessFile.open0(Native Method)
    at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
    at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
    at org.eclipse.aether.connector.basic.PartialFile$LockFile.tryLock(PartialFile.java:123)
    at org.eclipse.aether.connector.basic.PartialFile$LockFile.lock(PartialFile.java:71)
    at org.eclipse.aether.connector.basic.PartialFile$LockFile.<init>(PartialFile.java:58)
    at org.eclipse.aether.connector.basic.PartialFile$Factory.newInstance(PartialFile.java:210)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:432)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
    ... 40 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

Any ideas? Thanks!

**Comment by cstritzke** [comment]
This looks a lot like some kind of access right problem. Don't know how to solve this other than by brute force deletion of parts of the m2 repository folder.

On the bright side: The updatesite server is running again :)

**Comment by ElisaRojas** [comment]
Yes, I was just about to say that... :)

I tried deleting parts of the m2 folder, but it didn't work, although it seems what you say... but I was not lucky :laughing: 

I'm closing the issue then, thank you @cstritzke !
